config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  devise_for :users, :controllers => {
                        :registrations => 'user/registrations',
  }
  #devise_for :users

  resources :user_stocks, except: [:show, :edit, :update]
  #resources :users, only: [:show]
  resources :users, only: [:show, :index, :edit, :update] do
    resources :articles, only: [:new]
  end
  resources :articles, except: [:new]
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'my_portfolio', to: "users#my_portfolio"

  get 'search_stocks', to: "stocks#search"

  get 'my_friends', to: "users#my_friends"

  get 'search_friends', to: "users#search"

  post 'add_friend', to: "users#add_friend"

  get 'blogs', to: "articles#blogs"

  get 'myposts', to: "articles#myposts"

  #resources :users do
  #  resources :articles
  #end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :articles

  belongs_to :role
  before_validation :set_default_role

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # User whatever other msg
    end
  end
  
  def full_name 
  	return "#{first_name} #{last_name}".strip if (first_name || last_name)
  	"Anonymous"
  end
  def can_add_stock?(ticker_symbol)
  	under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
  	(user_stocks.count < 10)
  end

  def stock_already_added?(ticker_symbol)
  	# this function find if valid stock or not then go to check if it already existed in database then won't let user add to Portfolio.
  	stock = Stock.find_by_ticker(ticker_symbol)
  	return false unless stock
  	user_stocks.where(stock_id: stock.id).exists? 
  	# The line above means: for example: u = User.first => u.user_stocks.where(stock_id: 1).exists? return true if exists or false if doesn't
  end

  def not_friends_with?(friend_id)
  	friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
  	users.reject { |user| user.id == self.id } #self mean the caller in this case current_user
  end

  def self.search(param)
  	return User.none if param.blank?

  	param.strip!
  	param.downcase!
  	(first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq #reference to this page http://guides.rubyonrails.org/v3.2/active_record_querying.html
  	#the above line will add up all result and then uniq to remove duplicate records.
  end

  def self.first_name_matches(param)
  	matches('first_name', param)
  end

  def self.last_name_matches(param)
  	matches('last_name', param)
  end

  def self.email_matches(param)
  	matches('email', param)
  end

  def self.matches(field_name, param)
  	where("lower(#{field_name}) like ?", "%#{param}%")
  	#Reference this page http://guides.rubyonrails.org/v3.2/active_record_querying.html
  	#Example: User.where("email like ?", "%@%") 
  	#Recommend querry by array method to avoid SQL injection exploits with String only.
  end

  def isAdmin?
    if self.role.name == "admin" 
      return true
    else
      return false
    end
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
    #self.role = Role.find(1)
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	before_action :configure_permitted_parameters if :devise_controller?

	def create
		#debugger
		build_resource(sign_up_params)

		resource.save
		yield resource if block_given?
		if resource.persisted?
		  if resource.active_for_authentication?
		    set_flash_message! :notice, :signed_up
		    sign_up(resource_name, resource)
		    respond_with resource, location: after_sign_up_path_for(resource)
		  else
		    set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
		    expire_data_after_sign_in!
		    respond_with resource, location: after_inactive_sign_up_path_for(resource)
		  end
		else
		  clean_up_passwords resource
		  set_minimum_password_length
		  response_to_sign_up_failure resource
		end
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
	end

	def response_to_sign_up_failure(resource)
		if resource.email == "" && resource.password == nil
			redirect_to root_path, alert: "Please fill out the form"
		elsif User.pluck(:email).include? resource.email
			redirect_to root_path, alert: "email already exists"
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_admin, only: [:index, :edit, :destroy, :update]
	
	def my_portfolio
		@user_stocks = current_user.stocks
		@user = current_user
	end

	def my_friends
		@friendships = current_user.friends
	end

	def search
		@users = User.search(params[:search_param])

		if @users
			@users = current_user.except_current_user(@users)
			render partial: "friends/lookup"
		else
			render status: :not_found, nothing: true
		end
	end

	def add_friend
		@friend = User.find(params[:friend])
		current_user.friendships.build(friend_id: @friend.id)

		if current_user.save
			redirect_to my_friends_path, notice: "Friend was successfully added!"
		else
			redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend"
		end
	end

	def show
		#debugger
		#@friend = User.find(params[:id])
		@user = User.find(params[:id])
		@user_stocks = @user.stocks
	end

	def index
=begin
		if params[:approved] == "false"
			@users = User.where(approved: false)
		else
			@users = User.all
		end
=end
		@users = current_user.except_current_user(User.all)
	end

	def edit
	  @user = User.find(params[:id])
	end

	def update
	  #debugger
	  @user = User.find(params[:id])
	  respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
	        format.json { render :show, status: :ok }
	      end
  	  end
	end

	private
		def set_user
	      @user = User.find(params[:id])
	    end
		def require_admin
			if current_user.role.name != 'admin'
				#flash[:error] = "You need admin permision to perform this action!"
				redirect_to root_path, :flash => { :error => "You need admin permision to perform this action!" }
			end
		end
		def user_params
			params.require(:user).permit(:approved, :role_id)
		end
end

app/views/users/edit.html.erb
<div class="page-small panel-default">
<div class="panel-heading">
<h4>Admin Edit User</h4>
</div>

<div class="panel-body">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Approved</th>
				<th>Role</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<%=form_for(@user) do |f| %>
					<td><%= f.label :name, @user.full_name %></td>
					<td><%= f.label :email, @user.email %></td>
					<td><%= f.select :approved, ["true", "false"], selected: @user.approved %></td>
					<td><%= f.collection_select(:role_id, Role.all, :id, :name) %></td>
					<td><%= f.submit class: "btn btn-primary btn-black" %></td>
				<% end %>
			</tr>
		</tbody>
	</table>
</div>
</div>

app/views/users/index.html.erb
<div class="page-small panel-default">
<div class="panel-heading">
<h4>Admin Page</h4>
</div>

<div class="panel-body">
	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan="4" class="header">
					<h2>List of Users</h2>
				</th>
			</tr>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Status</th>
				<th>Role</th>
				<th colspan="2">Actions</th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<%= form_for(user) do |f| %>
				<td><%= f.label :name, user.full_name %></td>
				<td><%= f.label :email, user.email %></td>
				<td><%= f.label :approved, user.approved ? "Active" : "Inactive" %><%#= f.select :approved, ['true', 'false'], selected: user.approved %></td>
				<td><%= f.label :role, user.role.name.capitalize %><%#= f.collection_select(:role_id, Role.all, :id, :name ) %></td>
				<td><%= link_to "Edit", edit_user_path(user) %></td>
				<td><%= link_to "Destroy", user, method: :delete, data: "Are you sure to delete?" %></td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

</div>

app/views/users/my_friends.html.erb
<div class="page-small panel-default">
<div class="panel-heading">
<h4>Search Friends</h4>
</div>

<div class="panel-body">
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan="3" class="header">
					<h2>My Friends</h2>
				</th>
			</tr>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Action</th>
			</tr>
		</thead>

		<tbody>
			<% @friendships.each do |friend| %>
			<tr>
				<td><%= friend.full_name %></td>
				<td><%= friend.email %></td>
				<td>
					<%= link_to 'View Profile', user_path(friend), class: "btn btn-primary btn-xs" %>
					<%= link_to 'Remove Friend', friendship_path(friend), 
										  :method => :delete,
										  :data => { :confirm => "Are you sure?"},
										  :class => "btn btn-xs btn-danger" %> 
				</td>	
			</tr>
			<% end %>
		</tbody>
	</table>

<% else %>
	<div class="row col-lg-12">
		<p class="lead">You don't have any friends yet. Please add some! </p>
	</div>

<% end %>
</div>
</div>

app/views/users/my_portfolio.html.erb
<div class="page-small panel-default">
<div class="panel-heading">
<h4>Search Stock</h4>
</div>
<div class="panel-body">
<%= render 'stocks/lookup' %>

<%= render 'stocks/list' %>
</div>
</div>

app/views/users/show.html.erb
<div class="page-small panel-default">
	<div class="panel-heading"> 
		<h4 align="center">Welcome to <%=@user.full_name %>'s page</h1>
	</div>
	<div class="panel-body">
		<dl class='dl-horizontal'>
			<dt><strong>Full Name:</strong></dt>
			<dd><%= @user.full_name %></dd>
			<dt><strong>Email:</strong></dt>
			<dd><%= @user.email %></dd>
		</dl>

		<% if @user.stocks.size > 0 %>
			<%= render 'stocks/list' %>
		<% else %>
			<p class="lead">This user is not tracking any stocks</p>
		<% end %>

		<%= link_to "Back", my_friends_path, class: "btn btn-black btn-primary" %>
	</div>
</div>