config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  devise_for :users, :controllers => {
                        :registrations => 'user/registrations',
  }
  #devise_for :users

  resources :user_stocks, except: [:show, :edit, :update]
  #resources :users, only: [:show]
  resources :users, only: [:show, :index, :edit, :update] do
    resources :articles, only: [:new]
  end
  resources :articles, except: [:new]
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'my_portfolio', to: "users#my_portfolio"

  get 'search_stocks', to: "stocks#search"

  get 'my_friends', to: "users#my_friends"

  get 'search_friends', to: "users#search"

  post 'add_friend', to: "users#add_friend"

  get 'blogs', to: "articles#blogs"

  get 'myposts', to: "articles#myposts"

  #resources :users do
  #  resources :articles
  #end
  
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:show, :index]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category_articles = @category.articles
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !current_user.isAdmin?
        flash[:danger] = "This action is required Admin role!"
        redirect_to categories_path
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <div class="col-sm-2"><%= f.label :name , :class => 'field-label-cust' %></div>
    <div class="col-sm-10"><%= f.text_field :name , placeholder: "Enter Category", :class => 'field-box-cust text-field-cust' %></div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-black btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-small panel-default">
	<div class="panel-heading">
		<h4>Editing Category</h4>
	</div>
	<div class="panel-body">
		<%= render 'form', category: @category %>

		<%= link_to 'Back', categories_path, :class => 'btn-devise' %>
	</div>
</div>

app/views/categories/index.html.erb
<div class="page-small panel-default">
    <p id="notice"><%= notice %></p>
  <div class="panel-heading">
    <h4>Categories</h4>
  </div>
  <div class="panel-body">
    <% if @categories.count > 0 %>
    <ul class="flex-container list-no-style">
      <% @categories.each do |category| %>
        <li class="flex-card-quarter">
          <div class="panel-item">
            <h5><%= link_to category.name, category_path(category) %></h5>
            <p><%= pluralize(category.articles.count, "articles") %></p>
            <% if current_user.isAdmin? %> 
            <%= link_to 'Edit', edit_category_path(category), :class => "btn btn-xs btn-primary" %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <% else %>
      <p>There is no category available now. Please add one!</p>
    <% end %>

    <%= link_to 'New Category', new_category_path, :class => 'btn btn-primary btn-black' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="page-small panel-default">
	<div class="panel-heading">
		<h4>New Category</h4>
	</div>
	<div class="panel-body">
		<%= render 'form', category: @category %>

		<%= link_to 'Back', categories_path, :class => 'btn-devise' %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="page-small panel-default">
	<p id="notice"><%= notice %></p>
	<div class="panel-heading">
		<h4><%= @category.name %></h4>
	</div>
	<div class="panel-body">
		<% if @category_articles.count > 0 %>
			<ul class="flex-container list-no-style">
			<% @category_articles.each do |article| %>
				<li class="flex-card-quarter">
				  <div class="panel-item">
				    <h5><%= link_to article.title, article_url(article) %></h5>
				    <%= image_tag(article.img_url, :class => 'thumbnail_img') %>
				    <p><%= article.description %></p>
				    <%#= link_to 'Edit', edit_category_path(category), :class => "btn btn-xs btn-primary" %>
				    <%#= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %>
				  </div>
				</li>
			<% end %>
			</ul>
		<% else %>
			<p>There is no category available now. Please add one!</p>
			<%= link_to 'Add New Article', new_user_article_path(current_user), :class=> 'btn btn-small btn-grey' %>
		<% end %>
	<%# if current_user.isAdmin? %>
		<%= link_to 'Edit', edit_category_path(@category), :class => 'btn btn-primary btn-black' %>
	<%# end %>
	<%= link_to 'Back', categories_path, :class => "btn-devise" %>
	</div>
</div>