config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  devise_for :users, :controllers => {
                        :registrations => 'user/registrations',
  }
  #devise_for :users

  resources :user_stocks, except: [:show, :edit, :update]
  #resources :users, only: [:show]
  resources :users, only: [:show, :index, :edit, :update] do
    resources :articles, only: [:new]
  end
  resources :articles, except: [:new]
  resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'my_portfolio', to: "users#my_portfolio"

  get 'search_stocks', to: "stocks#search"

  get 'my_friends', to: "users#my_friends"

  get 'search_friends', to: "users#search"

  post 'add_friend', to: "users#add_friend"

  get 'blogs', to: "articles#blogs"

  get 'myposts', to: "articles#myposts"

  #resources :users do
  #  resources :articles
  #end
  
end

app/views/layouts/_drawer.html.erb
<% if !current_user %>
<div id="drawer" class="drawer-right">
	<div class="drawer-container">
	  <div class="drawer-header">
	    <h4><%= t('.sign_in', default: 'Sign in') %></h4>
	    <%= link_to "", "#", class: "drawer-close" %>
	  </div>
	  <div class="drawer-body">
	    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { role: 'form', id: 'form_sign_in' }) do |f| %>
	      <div class="form-group form-group-cust">
	        <%= f.label :email %>
	        <%= f.email_field :email, autofocus: true, id: 'user_email_sign_in', class: 'form-control form-control-cust' %>
	      </div>
	      <div class="form-group form-group-cust">
	        <%= f.label :password %>
	        <%= f.password_field :password, autocomplete: 'off', id: 'user_password_sign_in', class: 'form-control form-control-cust' %>
	      </div>
	      <% if devise_mapping.rememberable? %>
	        <div class="checkbox checkbox-cust">
	          <%= f.label :remember_me do %>
	            <%= f.check_box :remember_me, id: 'remember_me_sign_in'%> <%= t('.remember_me', default: 'Remember me') %>
	          <% end %>
	        </div>
	      <% end %>
	      <%= f.submit  t('.sign_in', default: 'Sign in'), class: 'btn btn-primary btn-black' %>
	    <% end %>
	  </div>
		<%= render 'devise/shared/links' %>
	</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid section-footer">
      <footer>
      	<div class="footer-main">
			<div class="footer-main-container">	
				<div class="footer-about">
					<%= image_tag('ivan_avatar.jpg', alt: "About Me") %>
					<p>My name is Ivan. Alumnus of ITU (MSE program). Like programming, swimming especailly soccer.
					   I am a fan of Chelsea and PES. My favorite programming language is Ruby. Front End and Back End Developer.
					   Also knowing component level repair for computer. Fell free to contact me at <%= mail_to 'duytran211189@gmail.com','duytran211189@gmail.com', class: 'underline-link' %> if you have any problem with your computer.
					</p>
					<!--<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard</p>-->
				</div>
				<div class="footer-links-container">
					<div class="footer-links">
						<ul>
							<li>About Me</li>
							<li>Contact Me</li>
							<li>FAQ</li>
							<li>Services</li>
						</ul>
					</div>
					<div class="footer-links">
						<ul>
							<li>About Me</li>
							<li>Contact Me</li>
							<li>FAQ</li>
							<li>Services</li>
						</ul>
					</div>
				</div>
				<div class="footer-social">
					<h4>Like & Share at:</h4>
					<ul class="social-links">
			            <li><a class="btn btn-social-icon btn-facebook">
			                    <span class="fa fa-facebook"></span>
			                </a>
			            </li>
			            <li><a class="btn btn-social-icon btn-twitter">
			                    <span class="fa fa-twitter"></span>
			                </a>
			            </li>
			            <li><a class="btn btn-social-icon btn-instagram">
			                    <span class="fa fa-instagram"></span>
			                </a>
			            </li>
			            <li><a class="btn btn-social-icon btn-pinterest">
			                    <span class="fa fa-pinterest"></span>
			                </a>
			            </li>
		    		</ul>
				</div>	
			</div>
      	</div>
        <div class="footer-bottom">
        	<p>&copy; Copyright 2018</p>
        </div>
      </footer>
</div>

app/views/layouts/_homecategory.html.erb
<div id="homecategory">
	<div class="title-box">
		<h2>Services</h2>
	</div>
	<div class="cat-two-panel">
		<div class="cat-panel-container panel-large">
			<div class="cat-panel-image" style="background-image: url(<%= image_path('Service/Macbook_Service.jpg') %>)">
				<a class="link-overlay">MacBook<br>Service</a>
			</div>
		</div>
		<div class="cat-panel-container panel-small">
			<div class="cat-panel-image" style="background-image: url(<%= image_path('Service/iPhone_Service.jpg') %>)">
				<a class="link-overlay">iPhone<br>Service</a>
			</div>
		</div>
		<div class="cat-panel-container panel-small">
			<div class="cat-panel-image" style="background-image: url(<%= image_path('Service/iPad_Service.jpg') %>)">
				<a class="link-overlay">iPad<br>Service</a>
			</div>
		</div>
		<div class="cat-panel-container panel-large">
			<div class="cat-panel-image" style="background-image: url(<%= image_path('Service/Watch_Service.jpg') %>)">
				<a class="link-overlay">Watch<br>Service</a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_homegallery.html.erb
<div id="homegallery">
	<h2>My Gallery</h2>
	<div id="homegallery-slider">
		<%= link_to "", class: "gallery-slideshow-link" do %>
			<h3>Component Repair</h3>
			<%= image_tag('Slider/Circuit_Slide.jpg', alt: "Component Repair") %>
		<% end %>
		<%= link_to "", class: "gallery-slideshow-link" do %>
			<h3>Watch Servie</h3>
			<%= image_tag('Slider/Watch_Repair_Slide.jpg', alt: "Watch Service") %>
		<% end %>
		<%= link_to "", class: "gallery-slideshow-link" do %>
			<h3>Video Chip Repair</h3>
			<%= image_tag('Slider/Video_Chip_Slide.jpg', alt: "Video Chip Repair") %>
		<% end %>

	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
		$('#homegallery-slider').slick({
			arrows: true,
			slidesToShow: 1,
			fade: true,
			slidesToScroll: 1,
			dots: true,
			autoplay: false,
			autoplaySpeed: 5000,
			prevArrow: '<div class="slick-prev"><i class="nav-arrow d-left"></i></div>',
    		nextArrow: '<div class="slick-next"><i class="nav-arrow d-right"></i></div>'
		});
})

</script>

app/views/layouts/_homeinfo.html.erb
<div id="homeinfo">
	<h2>Welcome to my page</h2>
	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	<a>See more</a>
</div>

app/views/layouts/_homenewestblog.html.erb
<div id="homeblog">
	<div class="homeblog-title-box">
		<h2>My Blog</h2>
		<hr>
	</div>
	<div id="homeblog-slider">
		<% @hp_articles.each do |article| %>
		<div class="blog-slideshow">
			<%= link_to article_path(article), class: "blog-slideshow-link" do %>
				<%= image_tag("#{article.img_url}", alt: "#{article.title}") %>
			
				<div class=blog-slideshow-title>
					<h4><%= article.description %></h4>
				</div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#homeblog-slider').slick({
			arrows: false,
			slidesToShow: 3,
			slidesToScroll: 1,
			dots: false,
			autoplay: true,
			autoplaySpeed: 5000,
			responsive: [
				{
					breakpoint: 990,
					settings: {
						slidesToShow: 2
					}
				},
				{
					breakpoint: 768,
					settings: {
						slidesToShow: 1
					}
				}
			]
		});
	});
</script>

app/views/layouts/_homeslider.html.erb
<div id="homeslider">
	<div class="home-slideshow">
		<a class="slideshow-image" style="background-image: url(<%= image_path('Slider/iMac_Slide.jpg') %>)">
		</a>	
		<div class="slideshow-text slideshow-text-left slideshow-text-white">
			<h1>Macbook Service</h1>
			<hr>
			<p>Expertise in Macbook repair. <br>No Fix, No Pay</p>
			<a href="">View Details <i class="nav-arrow d-right"></i></a>
		</div>
	</div>

	<div class="home-slideshow">
		<a class="slideshow-image" style="background-image: url(<%= image_path('Slider/Circuit_Slide.jpg') %>)">
		</a>	
		<div class="slideshow-text slideshow-text-left slideshow-text-white">
			<h1>Component Level <br>Repair</h1>
			<hr>
			<p>Expertise in Soldering, <br>Rework Job</p>
			<a href="">View Details <i class="nav-arrow d-right"></i></a>
		</div>
	</div>

	<div class="home-slideshow">
		<a class="slideshow-image" style="background-image: url(<%= image_path('Slider/Video_Chip_Slide.jpg') %>)">
		</a>	
		<div class="slideshow-text slideshow-text-right slideshow-text-white">
			<h1>Video Chip <br>Problem</h1>
			<hr>
			<p>Yes, We Fix</p>
			<a href="">View Details <i class="nav-arrow d-right"></i></a>
		</div>
	</div>

	<div class="home-slideshow">
		<a class="slideshow-image" style="background-image: url(<%= image_path('Slider/iPhone_Water_Slide.jpg') %>)">
		</a>	
		<div class="slideshow-text slideshow-text-left slideshow-text-white">
			<h1>Water Damaged <br>iPhone</h1>
			<hr>
			<p>No worries! <br>Let We Take Care Of It</p>
			<a href="">View Details <i class="nav-arrow d-right"></i></a>
		</div>
	</div>

	<div class="home-slideshow">
		<a class="slideshow-image" style="background-image: url(<%= image_path('Slider/Watch_Repair_Slide.jpg') %>)">
		</a>	
		<div class="slideshow-text slideshow-text-right slideshow-text-white">
			<h1>Watch Service</h1>
			<hr>
			<p>Battery Replacement <br>Lifetime Warranty</p>
			<a href="">View Details <i class="nav-arrow d-right"></i></a>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#homeslider').slick({
			lazyload: 'progressive',
			arrows: false,
			dots: true,
			slidesToScroll: 1,
			autoplay: true,
			autoplaySpeed: 5000
		});
	});
</script>

app/views/layouts/_login_drawer.html.erb
<div>

</div>

app/views/layouts/_navigation.html.erb
 <div class="navbar navbar-default navbar-fixed-top is-moved-by-drawer">
  <div class="container">
      <div class="navbar-header">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag('ivan_avatar.jpg', alt: "About Me", class: "about-avatar-sml") %>
          <span style="margin-left: 15px;">Hi there !</span>
        <% end %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar-responsive" class="navbar-collapse collapse navbar-responsive-collapse ">
        <% if current_user %>
          <ul class="nav navbar-nav" id="navbar-underlying-link">
            <!--<li><%#= link_to "My Portfolio", my_portfolio_path, class: 'navbar-menu-link nav-active'  %></li>-->
            <%#= link_to "My Profile", edit_user_registration_path(current_user), class: 'navbar-menu-link' %>
            <!--<li><%#= link_to "My Friends", my_friends_path, class: 'navbar-menu-link' %></li>-->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle navbar-menu-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
                <% end %>
                <li><%= link_to "All Categories", categories_path %> </li>
              </ul>
            </li>
            <li><%= link_to "Blog", blogs_path, class: 'navbar-menu-link' %></li>
            
          </ul>
          <ul class="nav navbar-right navbar-right-cust">
            <li class="user-name text-right">
              <i class="fa fa-user"></i>
              <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
              <div class="account-links">
                <ul>
                  <% if current_user.isAdmin? %>
                  <li><%= link_to "Admin", users_path %></li>
                  <% end %>
                  <li><%= link_to "My Profile", edit_user_registration_path(current_user) %></li>
                  <li><%= link_to "My Posts", articles_path %></li>
                  <li><%= link_to "Create Blog", new_user_article_path(current_user) %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, class: "nav-btn-logout", method: :delete %></li>
                </ul>
              </div>
            </li>
            <li class="logout skip-desktop">
              <%= link_to "Logout", destroy_user_session_path, class: "nav-btn-logout", method: :delete %>
            </li>
          </ul>

        <% else %>
        <ul class="nav navbar-nav" id="navbar-underlying-link">
           <li class="dropdown">
             <a href="#" class="dropdown-toggle navbar-menu-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <li><%= link_to "All Categories", categories_path %> </li>
            </ul>
           </li>
           <li><%= link_to "Blog", blogs_path, class: 'navbar-menu-link' %></li>
        </ul>
          <ul class="nav navbar-right navbar-right-cust">
            <li class="navbar-right-link"><%= link_to "Login", "#login", class: "drawer-sign-in"  %></li>
            <li class="navbar-right-link"><%= link_to "Signup", "#sign_up", class: "modal-sign-up-link", data: { toggle: 'collapse', target: '.navbar-responsive-collapse'} %></li>
          </ul>
        <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
  $('.navbar-menu-link').on("mouseover", function(){
    $(this).addClass("nav-active");

    $(this).closest('.navbar-nav').find('li').find('a').not(this).each(function(){
      $(this).removeClass('nav-active');
    });
  })
})

</script>

app/views/layouts/_sign_up_modal.html.erb
<% if !current_user %>
<div class="modal" id="sign_up">
  <div class="modal-container">
    <div class="modal-close"></div>
    <div class="modal-content">
      <div class="modal-header">
        <h4><%= t('.sign_up', default: 'Sign up') %></h4>
        
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { role: 'form', id: 'form-sign-up' } ) do |f| %>
          <div class="form-group form-group-cust">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true, id: 'user_email_sign_up1', class: 'form-control form-control-cust' %>
          </div>
          <div class="form-group form-group-cust">
            <div class="col-md-6 no-padding">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, id: 'user_first_name_sign_up1', class: 'form-control form-control-cust' %>
            </div>
            <div class="col-md-6 no-padding left-padding">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, id: 'user_last_name_sign_up1', class: 'form-control form-control-cust' %>
            </div>
          </div>
          
          <div class="form-group form-group-cust">
            <%= f.label :password %>
            <%= f.password_field :password, id: 'user_password_sign_up1', class: 'form-control form-control-cust' %>
          </div>
          <div class="form-group form-group-cust">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, id: 'user_password_confirmation_sign_up1', class: 'form-control form-control-cust' %>
          </div>
          <p>By creating an account you agree to our <strong><%= link_to "Term & Privacy" %></strong></p>
          <%= f.submit t('.sign_up', default: 'Sign up'), class: 'btn btn-primary btn-black' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% if content_for?(:head) %>
        <%= yield(:head) %>
    <% end %>
    <title><%= content_for?(:title) ? yield(:title) : "Ivan's Website" %></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div id="fb-root"></div>
        <script>
            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=370871753405816&autoLogAppEvents=1';
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
    <%= render 'layouts/drawer' %>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/sign_up_modal' %>
    <div class="main-wrapper is-moved-by-drawer">   
        <div class="alert-container">
            <%= bootstrap_flash %>
        </div>         
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>